[package]
name = "pharmacy"
version = "0.1.0"
authors = ["m0ssc0de"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
actix-web = "2.0"
actix-rt = "1.0"
serde = "1.0"
serde_derive = "1.0"